# Generated by Django 5.0.4 on 2025-03-02 17:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_bailleur_departement_periode_region_typedindicateur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicateur',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicateur',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='typedindicateur',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typedindicateur',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
