# Generated by Django 5.1.6 on 2025-03-09 16:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_indicateur_created_at_indicateur_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='periode',
            name='date_debut',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='periode',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('libelle', models.CharField(max_length=255, unique=True)),
                ('cout_programme', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bailleur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.bailleur')),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammeIndicateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indicateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.indicateur')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.programme')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('programme', 'indicateur'), name='unique_programme_indicateur')],
            },
        ),
    ]
