# Generated by Django 5.1.6 on 2025-04-09 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_periodicite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField()),
                ('date_collecte', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('indicateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.indicateur')),
            ],
        ),
        migrations.DeleteModel(
            name='Periodicite',
        ),
        migrations.AddField(
            model_name='programmeindicateur',
            name='periodicite',
            field=models.CharField(choices=[('journalier', 'Journalier'), ('hebdomadaire', 'Hebdomadaire'), ('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('semestriel', 'Semestriel'), ('annuel', 'Annuel')], default='mensuel', max_length=20),
        ),
    ]
