# Generated by Django 5.1.6 on 2025-04-14 17:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_collecte_delete_periodicite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collecte',
            name='date_debut',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collecte',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
