# Generated by Django 5.1.6 on 2025-04-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_collecte_date_debut_collecte_date_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collecte',
            name='date_collecte',
            field=models.DateField(auto_now_add=True),
        ),
    ]
