# Generated by Django 5.1.6 on 2025-04-16 13:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_collecte_date_collecte'),
    ]

    operations = [
        migrations.AddField(
            model_name='collecte',
            name='slug',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
