# Generated by Django 5.1.6 on 2025-04-16 13:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_collecte_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collecte',
            name='slug',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
