# Generated by Django 5.1.6 on 2025-04-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_collecte_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='collecte',
            name='valeur_prevu',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
