# Generated by Django 5.1.6 on 2025-04-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_collecte_valeur_prevu'),
    ]

    operations = [
        migrations.AddField(
            model_name='collecte',
            name='periode_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='collecte',
            name='valeur',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
