# Generated by Django 5.1.6 on 2025-04-23 15:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_collecte_periode_label_alter_collecte_valeur'),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheCollecteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('niveau', models.CharField(choices=[('region', 'Région'), ('departement', 'Département'), ('commune', 'Commune')], max_length=20)),
                ('libelle', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FicheCollecteDonnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('unite_mesure', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donnees', to='api.fichecollecteconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='FicheCollecteValeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField()),
                ('date_collecte', models.DateField(auto_now_add=True)),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.commune')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.departement')),
                ('donnee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valeurs', to='api.fichecollectedonnee')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.region')),
            ],
        ),
    ]
