# Generated by Django 5.1.6 on 2025-04-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_fichecollecteconfiguration_fichecollectedonnee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichecollectevaleur',
            name='valeur',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
