# Generated by Django 5.1.6 on 2025-04-25 17:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_fichecollectevaleur_valeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichecollectedonnee',
            name='slug',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='fichecollectevaleur',
            name='slug',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
