# Generated by Django 5.1.6 on 2025-05-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_fichecollectedonnee_slug_fichecollectevaleur_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='collecte',
            name='periode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichecollectevaleur',
            name='periode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
